services:
  backend:
    image: maven:3.9-eclipse-temurin-17
    container_name: spring_app
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "cd /app && mvn clean package -DskipTests && java -jar target/*.jar",
      ]

  frontend:
    image: node:22-alpine
    container_name: react_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]

  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: defense_spring_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
